apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  labels: 
    app: my-app
spec: 
  containers:
    - name: nginx-container
      image: nginx
      resources:
        limits:
          cpu: "0.5"
          memory: "256Mi"
