apiVersion: v1
kind: ReplicationController
metadata:
    name: myapp-rc
    labbels:
        app: myapp
        type: front-end
spec:
    template:
        metadata:
            name: myapp-pod
            labels:
                app: myapp
                type: front-end
            sppec:
                containers:
                - name: nginx-container
                  image: nginx
    replicas: 3