apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: myapp-rs
    labbels:
        app: myapp
        type: front-end
spec:
    template:
        metadata:
            name: myapp-pod
            labels:
                app: myapp
                type: front-end
            sppec:
                containers:
                - name: nginx-container
                  image: nginx
    replicas: 3
    selector:
        matchLabels:
            type: front-end